list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/")
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/packages")

set(THIRD_PARTY "third-party" CACHE STRING "3rdparty folder for project dependencies. [Don't change this variable.]")

find_package(Git)
if(Git_FOUND)
  message("Git found: ${GIT_EXECUTABLE}")
endif()

find_package(CURL REQUIRED)
if(TARGET CURL::libcurl)
  list(APPEND LIB_MODULES CURL::libcurl)
else()
  list(APPEND LIB_MODULES ${CURL_LIBRARIES})
  list(APPEND LIB_TARGET_INCLUDE_DIRECTORIES ${CURL_INCLUDE_DIRS})
endif()

# Prefer CMake package configs first, then fallback to pkg-config.
find_package(jsoncpp CONFIG QUIET)
if(TARGET jsoncpp_lib)
  list(APPEND LIB_MODULES jsoncpp_lib)
elseif(TARGET JsonCpp::JsonCpp)
  list(APPEND LIB_MODULES JsonCpp::JsonCpp)
elseif(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/third-party/JSon/json-src/CMakeLists.txt")
  set(JSONCPP_WITH_TESTS OFF CACHE BOOL "Disable jsoncpp tests" FORCE)
  set(JSONCPP_WITH_POST_BUILD_UNITTEST OFF CACHE BOOL "Disable jsoncpp post build test" FORCE)
  set(JSONCPP_WITH_CMAKE_PACKAGE OFF CACHE BOOL "Disable jsoncpp package install targets" FORCE)
  add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/third-party/JSon/json-src
                   third-party/jsoncpp
                   EXCLUDE_FROM_ALL)
  if(TARGET jsoncpp_lib)
    list(APPEND LIB_MODULES jsoncpp_lib)
  elseif(TARGET JsonCpp::JsonCpp)
    list(APPEND LIB_MODULES JsonCpp::JsonCpp)
  else()
    message(FATAL_ERROR "Vendored jsoncpp was found, but no expected target was exported.")
  endif()
else()
  find_package(PkgConfig REQUIRED)
  pkg_check_modules(JSONCPP REQUIRED IMPORTED_TARGET jsoncpp)
  list(APPEND LIB_MODULES PkgConfig::JSONCPP)
endif()
